import GameButton from "@/components/GameButton";
import Head from "next/head";

export default function Home() {
  let score = 0;

  function clickMe() {
    score++;
    console.log("your score:", score);
  }

  return (
    <>
      <Head>
        <title>My first game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen bg-gray-800 flex justify-center items-center">
        <GameButton onClick={clickMe}>Press Start!</GameButton>
      </div>
    </>
  );
}
